# Generated by Django 3.2.9 on 2021-12-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0004_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
