# Generated by Django 3.2.8 on 2021-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211018_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='/images/default_profile_pic.png', upload_to='profile_pic/%Y/%m/%d/'),
        ),
    ]
