# Generated by Django 3.2.8 on 2021-10-21 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='images/default_profile_pic.png', upload_to='profile_pic/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
